In [ ]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

In [ ]:
from google.colab import files

uploaded = files.upload()

file_name = next(iter(uploaded))
df = pd.read_csv(file_name)

print("Dataset loaded successfully!")
print("Number of Rows    :", df.shape[0])
print("Number of Columns :", df.shape[1])

display(df.head())

Saving multi_coin_trading_100000_rows.csv to multi_coin_trading_100000_rows.csv
Dataset loaded successfully!
Number of Rows    : 100000
Number of Columns : 13

,Date,Coin,Open,High,Low,Close,Volume,Return_1D,MA_7,MA_14,Volatility_7D,Future_Return_1D,Target
0,01-01-2018,ADA-USD,0.197271,0.203853,0.196598,0.199858,1074932.488,NaN,NaN,NaN,NaN,0.065046,1.0
1,02-01-2018,ADA-USD,0.212000,0.213596,0.208394,0.212858,6118457.574,0.065046,NaN,NaN,NaN,0.013226,1.0
2,03-01-2018,ADA-USD,0.216565,0.217562,0.210443,0.215673,2543173.061,0.013226,NaN,NaN,NaN,-0.018997,0.0
3,04-01-2018,ADA-USD,0.214111,0.216133,0.210629,0.211576,1441831.076,-0.018997,NaN,NaN,NaN,0.021628,1.0
4,05-01-2018,ADA-USD,0.217005,0.219534,0.210960,0.216152,6722193.059,0.021628,NaN,NaN,NaN,-0.010849,0.0

In [ ]:
print(df.info())

print(df.shape)

df = df.drop_duplicates()

print(df["Date"].isnull().sum())

df = df.dropna(subset=["Date"])
df = df.sort_values(
    by=["Coin", "Date"]
).reset_index(drop=True)

print("Rows    :", df.shape[0])
print("Columns :", df.shape[1])
print(df.isnull().sum())

display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              100000 non-null  object
 1   Coin              100000 non-null  object
 2   Open              100000 non-null  float64
 3   High              100000 non-null  float64
 4   Low               100000 non-null  float64
 5   Close             100000 non-null  float64
 6   Volume            100000 non-null  float64
 7   Return_1D         99992 non-null   float64
 8   MA_7              99952 non-null   float64
 9   MA_14             99896 non-null   float64
 10  Volatility_7D     99944 non-null   float64
 11  Future_Return_1D  99992 non-null   float64
 12  Target            99992 non-null   float64
dtypes: float64(11), object(2)
memory usage: 9.9+ MB
None
(100000, 13)
0
Rows    : 100000
Columns : 13
Date                  0
Coin                  0
Open                  0
High                  0
Low                   0
Close                 0
Volume                0
Return_1D             8
MA_7                 48
MA_14               104
Volatility_7D        56
Future_Return_1D      8
Target                8
dtype: int64

,Date,Coin,Open,High,Low,Close,Volume,Return_1D,MA_7,MA_14,Volatility_7D,Future_Return_1D,Target
0,01-01-2018,ADA-USD,0.197271,0.203853,0.196598,0.199858,1.074932e+06,NaN,NaN,NaN,NaN,0.065046,1.0
1,01-01-2019,ADA-USD,0.072616,0.073110,0.070652,0.072297,4.205577e+06,0.065024,0.070702,0.071034,0.048161,-0.000343,0.0
2,01-01-2020,ADA-USD,0.049355,0.049637,0.048065,0.049373,2.216525e+06,0.059746,0.050900,0.052028,0.041361,0.005723,1.0
3,01-01-2021,ADA-USD,0.091439,0.094153,0.090375,0.091582,4.119643e+06,-0.011619,0.089264,0.087446,0.033335,0.033459,1.0
4,01-01-2022,ADA-USD,0.085362,0.086910,0.082735,0.084701,1.134072e+07,-0.026146,0.087074,0.089815,0.030989,-0.014579,0.0

In [ ]:
print("Number of Different Coins:",
      df["Coin"].nunique())

print("\nCoin Names:")
print(df["Coin"].unique())

print("\nRecords Per Coin:")
print(df["Coin"].value_counts())

Number of Different Coins: 8

Coin Names:
['ADA-USD' 'AVAX-USD' 'BNB-USD' 'BTC-USD' 'DOGE-USD' 'ETH-USD' 'SOL-USD'
 'XRP-USD']

Records Per Coin:
Coin
ADA-USD     12500
AVAX-USD    12500
BNB-USD     12500
BTC-USD     12500
DOGE-USD    12500
ETH-USD     12500
SOL-USD     12500
XRP-USD     12500
Name: count, dtype: int64

In [ ]:
print("Final Dataset Shape:", df.shape)

print("\nTotal Missing Values:",
      df.isnull().sum().sum())

print("Total Duplicate Rows:",
      df.duplicated().sum())

display(df.head(10))

Final Dataset Shape: (100000, 13)

Total Missing Values: 232
Total Duplicate Rows: 0

,Date,Coin,Open,High,Low,Close,Volume,Return_1D,MA_7,MA_14,Volatility_7D,Future_Return_1D,Target
0,01-01-2018,ADA-USD,0.197271,0.203853,0.196598,0.199858,1.074932e+06,NaN,NaN,NaN,NaN,0.065046,1.0
1,01-01-2019,ADA-USD,0.072616,0.073110,0.070652,0.072297,4.205577e+06,0.065024,0.070702,0.071034,0.048161,-0.000343,0.0
2,01-01-2020,ADA-USD,0.049355,0.049637,0.048065,0.049373,2.216525e+06,0.059746,0.050900,0.052028,0.041361,0.005723,1.0
3,01-01-2021,ADA-USD,0.091439,0.094153,0.090375,0.091582,4.119643e+06,-0.011619,0.089264,0.087446,0.033335,0.033459,1.0
4,01-01-2022,ADA-USD,0.085362,0.086910,0.082735,0.084701,1.134072e+07,-0.026146,0.087074,0.089815,0.030989,-0.014579,0.0
5,01-01-2023,ADA-USD,0.162387,0.166164,0.161044,0.162981,2.268005e+06,0.002588,0.167567,0.167273,0.028802,-0.008813,0.0
6,01-01-2024,ADA-USD,0.251786,0.252821,0.244114,0.251161,5.212018e+06,0.035426,0.241815,0.233667,0.018531,-0.028328,0.0
7,01-01-2025,ADA-USD,0.128848,0.129904,0.123335,0.126974,3.010028e+06,0.030661,0.119991,0.117390,0.022551,0.033465,1.0
8,01-01-2026,ADA-USD,0.345171,0.346329,0.341340,0.345175,9.049391e+06,0.040562,0.349661,0.359299,0.028448,0.079513,1.0
9,01-01-2027,ADA-USD,0.323031,0.329808,0.321889,0.323063,8.337128e+06,0.010243,0.344318,0.363739,0.035444,-0.021321,0.0

In [ ]:
print("Dataset Shape:")
print(df.shape)

print("\nDataset Columns:")
print(df.columns.tolist())

print("\nStatistical Summary:")
display(df.describe())

coin_counts = df["Coin"].value_counts()

print("Number of Records for Each Coin:")
display(coin_counts)

Dataset Shape:
(100000, 13)

Dataset Columns:
['Date', 'Coin', 'Open', 'High', 'Low', 'Close', 'Volume', 'Return_1D', 'MA_7', 'MA_14', 'Volatility_7D', 'Future_Return_1D', 'Target']

Statistical Summary:

,Open,High,Low,Close,Volume,Return_1D,MA_7,MA_14,Volatility_7D,Future_Return_1D,Target
count,1.000000e+05,1.000000e+05,1.000000e+05,1.000000e+05,1.000000e+05,99992.000000,1.000000e+05,1.000000e+05,99984.000000,99992.000000,99992.000000
mean,2.540251e+06,2.587834e+06,2.492847e+06,2.540018e+06,5.388692e+06,0.426472,2.536905e+06,2.535365e+06,0.934042,0.426472,0.580126
std,1.418906e+07,1.445465e+07,1.392401e+07,1.418712e+07,6.982322e+06,1.073772,1.095790e+07,9.082924e+06,0.513045,1.073772,0.493540
min,2.820433e-03,2.856248e-03,2.771133e-03,2.821298e-03,2.612281e+04,-0.999997,2.990421e-03,2.990421e-03,0.087634,-0.999997,0.000000
25%,1.170727e+00,1.193245e+00,1.148740e+00,1.171057e+00,1.662456e+06,-0.281932,2.079274e+00,4.501014e+00,0.605269,-0.281932,0.000000
50%,4.400572e+01,4.484827e+01,4.306203e+01,4.394541e+01,3.270159e+06,0.151624,9.863440e+01,1.488011e+02,0.836134,0.151624,1.000000
75%,1.000135e+04,1.016866e+04,9.819103e+03,9.993108e+03,6.399160e+06,0.829631,2.211501e+04,1.845104e+04,1.132900,0.829631,1.000000
max,2.505829e+08,2.579637e+08,2.477241e+08,2.510359e+08,2.184409e+08,40.982733,1.047020e+08,6.084882e+07,15.511957,40.982733,1.000000

Number of Records for Each Coin:

Coin
ADA-USD     12500
AVAX-USD    12500
BNB-USD     12500
BTC-USD     12500
DOGE-USD    12500
ETH-USD     12500
SOL-USD     12500
XRP-USD     12500
Name: count, dtype: int64

In [ ]:

df = df.sort_values(
    ["Coin", "Date"]
).reset_index(drop=True)

df["Return_1D"] = (
    df.groupby("Coin")["Close"]
      .pct_change()
)

print("Return_1D created successfully!")

display(
    df[
        ["Date", "Coin", "Close", "Return_1D"]
    ].head(10)
)

Return_1D created successfully!

         Date     Coin     Close  Return_1D
0  01-01-2018  ADA-USD  0.199858        NaN
1  01-01-2019  ADA-USD  0.072297  -0.638259
2  01-01-2020  ADA-USD  0.049373  -0.317082
3  01-01-2021  ADA-USD  0.091582   0.854913
4  01-01-2022  ADA-USD  0.084701  -0.075139
5  01-01-2023  ADA-USD  0.162981   0.924196
6  01-01-2024  ADA-USD  0.251161   0.541047
7  01-01-2025  ADA-USD  0.126974  -0.494453
8  01-01-2026  ADA-USD  0.345175   1.718468
9  01-01-2027  ADA-USD  0.323063  -0.064058

In [ ]:
df["MA_7"] = (
    df.groupby("Coin")["Close"]
      .transform(
          lambda x: x.rolling(
              window=7,
              min_periods=1
          ).mean()
      )
)

print("MA_7 created successfully!")

display(
    df[
        ["Date", "Coin", "Close", "MA_7"]
    ].head(10)
)

MA_7 created successfully!

         Date     Coin     Close      MA_7
0  01-01-2018  ADA-USD  0.199858  0.199858
1  01-01-2019  ADA-USD  0.072297  0.136077
2  01-01-2020  ADA-USD  0.049373  0.107176
3  01-01-2021  ADA-USD  0.091582  0.103278
4  01-01-2022  ADA-USD  0.084701  0.099562
5  01-01-2023  ADA-USD  0.162981  0.110132
6  01-01-2024  ADA-USD  0.251161  0.130279
7  01-01-2025  ADA-USD  0.126974  0.119867
8  01-01-2026  ADA-USD  0.345175  0.158850
9  01-01-2027  ADA-USD  0.323063  0.197948

In [ ]:
df["MA_14"] = (
    df.groupby("Coin")["Close"]
      .transform(
          lambda x: x.rolling(
              window=14,
              min_periods=1
          ).mean()
      )
)

print("MA_14 created successfully!")

display(
    df[
        ["Date", "Coin", "Close", "MA_14"]
    ].head(10)
)

MA_14 created successfully!

         Date     Coin     Close     MA_14
0  01-01-2018  ADA-USD  0.199858  0.199858
1  01-01-2019  ADA-USD  0.072297  0.136077
2  01-01-2020  ADA-USD  0.049373  0.107176
3  01-01-2021  ADA-USD  0.091582  0.103278
4  01-01-2022  ADA-USD  0.084701  0.099562
5  01-01-2023  ADA-USD  0.162981  0.110132
6  01-01-2024  ADA-USD  0.251161  0.130279
7  01-01-2025  ADA-USD  0.126974  0.129866
8  01-01-2026  ADA-USD  0.345175  0.153789
9  01-01-2027  ADA-USD  0.323063  0.170717

In [ ]:
df["Volatility_7D"] = (
    df.groupby("Coin")["Return_1D"]
      .transform(
          lambda x: x.rolling(
              window=7,
              min_periods=2
          ).std()
      )
)

print("Volatility_7D created successfully!")

display(
    df[
        ["Date", "Coin", "Return_1D", "Volatility_7D"]
    ].head(10)
)

Volatility_7D created successfully!

         Date     Coin  Return_1D  Volatility_7D
0  01-01-2018  ADA-USD        NaN            NaN
1  01-01-2019  ADA-USD  -0.638259            NaN
2  01-01-2020  ADA-USD  -0.317082       0.227106
3  01-01-2021  ADA-USD   0.854913       0.785948
4  01-01-2022  ADA-USD  -0.075139       0.642062
5  01-01-2023  ADA-USD   0.924196       0.704714
6  01-01-2024  ADA-USD   0.541047       0.650246
7  01-01-2025  ADA-USD  -0.494453       0.651338
8  01-01-2026  ADA-USD   1.718468       0.791864
9  01-01-2027  ADA-USD  -0.064058       0.755959

In [ ]:
df["Future_Return_1D"] = (
    df.groupby("Coin")["Close"]
      .shift(-1) / df["Close"] - 1
)

print("Future_Return_1D created successfully!")

display(
    df[
        [
            "Date",
            "Coin",
            "Close",
            "Future_Return_1D"
        ]
    ].head(10)
)

Future_Return_1D created successfully!

         Date     Coin     Close  Future_Return_1D
0  01-01-2018  ADA-USD  0.199858         -0.638259
1  01-01-2019  ADA-USD  0.072297         -0.317082
2  01-01-2020  ADA-USD  0.049373          0.854913
3  01-01-2021  ADA-USD  0.091582         -0.075139
4  01-01-2022  ADA-USD  0.084701          0.924196
5  01-01-2023  ADA-USD  0.162981          0.541047
6  01-01-2024  ADA-USD  0.251161         -0.494453
7  01-01-2025  ADA-USD  0.126974          1.718468
8  01-01-2026  ADA-USD  0.345175         -0.064058
9  01-01-2027  ADA-USD  0.323063         -0.632964

In [ ]:
df["Target"] = np.where(
    df["Future_Return_1D"] > 0,
    1,
    0
)

# Last row of each coin has no future value
# so mark it as missing
last_rows = (
    df.groupby("Coin")
      .tail(1)
      .index
)

df.loc[last_rows, "Target"] = np.nan

print("Target created successfully!")

display(
    df[
        [
            "Date",
            "Coin",
            "Close",
            "Future_Return_1D",
            "Target"
        ]
    ].head(15)
)

Target created successfully!

          Date     Coin     Close  Future_Return_1D  Target
0   01-01-2018  ADA-USD  0.199858         -0.638259     0.0
1   01-01-2019  ADA-USD  0.072297         -0.317082     0.0
2   01-01-2020  ADA-USD  0.049373          0.854913     1.0
3   01-01-2021  ADA-USD  0.091582         -0.075139     0.0
4   01-01-2022  ADA-USD  0.084701          0.924196     1.0
5   01-01-2023  ADA-USD  0.162981          0.541047     1.0
6   01-01-2024  ADA-USD  0.251161         -0.494453     0.0
7   01-01-2025  ADA-USD  0.126974          1.718468     1.0
8   01-01-2026  ADA-USD  0.345175         -0.064058     0.0
9   01-01-2027  ADA-USD  0.323063         -0.632964     0.0
10  01-01-2028  ADA-USD  0.118576         -0.824120     0.0
11  01-01-2029  ADA-USD  0.020855         -0.329360     0.0
12  01-01-2030  ADA-USD  0.013986          0.229001     1.0
13  01-01-2031  ADA-USD  0.017189         -0.518571     0.0
14  01-01-2032  ADA-USD  0.008275          0.144978     1.0

In [ ]:
print(
    df["Target"]
    .value_counts(dropna=False)
)
target_by_coin = pd.crosstab(
    df["Coin"],
    df["Target"]
)

print("UP/DOWN Distribution by Coin:")

display(target_by_coin)

Target
1.0    58008
0.0    41984
NaN        8
Name: count, dtype: int64
UP/DOWN Distribution by Coin:

Target     0.0   1.0
Coin
ADA-USD   6347  6152
AVAX-USD  6077  6422
BNB-USD   5662  6837
BTC-USD   5472  7027
DOGE-USD  5009  7490
ETH-USD   3576  8923
SOL-USD   4997  7502
XRP-USD   4844  7655

In [ ]:
features = [
    "Open",
    "High",
    "Low",
    "Close",
    "Volume",
    "Return_1D",
    "MA_7",
    "MA_14",
    "Volatility_7D"
]

target = "Target"

print("ML Features:")
for feature in features:
    print("-", feature)

print("\nTarget:")
print("-", target)

ML Features:
- Open
- High
- Low
- Close
- Volume
- Return_1D
- MA_7
- MA_14
- Volatility_7D

Target:
- Target

In [ ]:
model_df = df.copy()

model_df = model_df.dropna(
    subset=features + ["Target"]
)

model_df["Target"] = (
    model_df["Target"]
    .astype(int)
)

print("Final ML Dataset Shape:")
print(model_df.shape)

print("\nMissing Values:")
print(model_df.isnull().sum())

display(model_df.head())

Final ML Dataset Shape:
(99976, 13)

Missing Values:
Date                0
Coin                0
Open                0
High                0
Low                 0
Close               0
Volume              0
Return_1D           0
MA_7                0
MA_14               0
Volatility_7D       0
Future_Return_1D    0
Target              0
dtype: int64

,Date,Coin,Open,High,Low,Close,Volume,Return_1D,MA_7,MA_14,Volatility_7D,Future_Return_1D,Target
2,01-01-2020,ADA-USD,0.049355,0.049637,0.048065,0.049373,2.216525e+06,-0.317082,0.107176,0.107176,0.227106,0.854913,1
3,01-01-2021,ADA-USD,0.091439,0.094153,0.090375,0.091582,4.119643e+06,0.854913,0.103278,0.103278,0.785948,-0.075139,0
4,01-01-2022,ADA-USD,0.085362,0.086910,0.082735,0.084701,1.134072e+07,-0.075139,0.099562,0.099562,0.642062,0.924196,1
5,01-01-2023,ADA-USD,0.162387,0.166164,0.161044,0.162981,2.268005e+06,0.924196,0.110132,0.110132,0.704714,0.541047,1
6,01-01-2024,ADA-USD,0.251786,0.252821,0.244114,0.251161,5.212018e+06,0.541047,0.130279,0.130279,0.650246,-0.494453,0

In [ ]:
train_parts = []
test_parts = []

# Split each cryptocurrency separately
for coin, group in model_df.groupby("Coin"):

    # Sort by date
    group = group.sort_values("Date").reset_index(drop=True)

    # Calculate 80% split point
    split_index = int(len(group) * 0.80)

    # First 80% = Training
    train_coin = group.iloc[:split_index]

    # Last 20% = Testing
    test_coin = group.iloc[split_index:]

    train_parts.append(train_coin)
    test_parts.append(test_coin)

# Combine all coins
train = pd.concat(
    train_parts,
    ignore_index=True
)

test = pd.concat(
    test_parts,
    ignore_index=True
)

X_train = train[features]
y_train = train["Target"]

X_test = test[features]
y_test = test["Target"]

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_test :", X_test.shape)
print("y_test :", y_test.shape)

print("Start Date:", train["Date"].min())
print("End Date  :", train["Date"].max())

print("Start Date:", test["Date"].min())
print("End Date  :", test["Date"].max())

print("Train Dataset Shape:", train.shape)
print("Test Dataset Shape :", test.shape)

X_train: (79976, 9)
y_train: (79976,)
X_test : (20000, 9)
y_test : (20000,)
Start Date: 01-01-2020
End Date  : 25-04-2050
Start Date: 25-04-2051
End Date  : 31-12-2050
Train Dataset Shape: (79976, 13)
Test Dataset Shape : (20000, 13)

In [ ]:
for coin in model_df["Coin"].unique():

    train_count = len(
        train[train["Coin"] == coin]
    )

    test_count = len(
        test[test["Coin"] == coin]
    )

    print(
        f"{coin:10s} -> "
        f"Train: {train_count:5d} | "
        f"Test: {test_count:5d}"
    )
print(y_train.value_counts())
print(y_test.value_counts())

ADA-USD    -> Train:  9997 | Test:  2500
AVAX-USD   -> Train:  9997 | Test:  2500
BNB-USD    -> Train:  9997 | Test:  2500
BTC-USD    -> Train:  9997 | Test:  2500
DOGE-USD   -> Train:  9997 | Test:  2500
ETH-USD    -> Train:  9997 | Test:  2500
SOL-USD    -> Train:  9997 | Test:  2500
XRP-USD    -> Train:  9997 | Test:  2500
Target
1    46356
0    33620
Name: count, dtype: int64
Target
1    11641
0     8359
Name: count, dtype: int64

In [ ]:
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

print("Training completed!")
y_pred = model.predict(X_test)

print("Prediction completed!")

accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")

comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print(
    classification_report( y_test,y_pred,target_names=["DOWN", "UP"]
    )
)

Training completed!
Prediction completed!
Accuracy: 81.86%
              precision    recall  f1-score   support

        DOWN       0.89      0.64      0.75      8359
          UP       0.79      0.94      0.86     11641

    accuracy                           0.82     20000
   macro avg       0.84      0.79      0.80     20000
weighted avg       0.83      0.82      0.81     20000

In [ ]:
import gradio as gr

coins = sorted(
    model_df["Coin"].unique()
)

print("Available Coins:")
print(coins)

latest_data = (
    model_df
    .sort_values(["Coin", "Date"])
    .groupby("Coin")
    .tail(1)
    .copy()
)

def predict_coin(coin_name):

    coin_data = latest_data[
        latest_data["Coin"] == coin_name
    ]

    if coin_data.empty:
        return (
            "No Data",
            "0.00%",
            "0.00%",
            "Random Forest",
            f"{accuracy * 100:.2f}%"
        )

    # Use the SAME features used during training
    X_input = coin_data[features].copy()

    # Clean input
    X_input = X_input.replace(
        [np.inf, -np.inf],
        np.nan
    ).fillna(0)

    # Random Forest prediction
    prediction = model.predict(X_input)[0]

    # Probability
    probability = model.predict_proba(X_input)[0]

    down_probability = probability[0] * 100
    up_probability = probability[1] * 100

    # UP / DOWN
    if prediction == 1:
        movement = "🟢 UP"
    else:
        movement = "🔴 DOWN"

    return (
        movement,
        f"{up_probability:.2f}%",
        f"{down_probability:.2f}%",
        "Random Forest",
        f"{accuracy * 100:.2f}%"
    )



with gr.Blocks(
    title="Cryptocurrency Prediction"
) as app:

    gr.Markdown(
        """
        #  Cryptocurrency Price Movement Prediction

        ### Random Forest Machine Learning Model
        """
    )

    coin_dropdown = gr.Dropdown(
        choices=coins,
        value=coins[0],
        label=" Select Cryptocurrency"
    )

    predict_button = gr.Button(
        " Predict UP / DOWN",
        variant="primary"
    )

    # Results in pridiction
    movement_output = gr.Textbox(
        label=" Predicted Movement"
    )

    up_output = gr.Textbox(
        label="🟢 UP Probability"
    )

    down_output = gr.Textbox(
        label="🔴 DOWN Probability"
    )

    model_output = gr.Textbox(
        label=" Model Used"
    )

    accuracy_output = gr.Textbox(
        label="Random Forest Test Accuracy"
    )

    predict_button.click(
        fn=predict_coin,
        inputs=coin_dropdown,
        outputs=[
            movement_output,
            up_output,
            down_output,
            model_output,
            accuracy_output
        ]
    )



app.launch(
    share=True
)